### ISSUE TITLE
往「开源中国」发布时遇到个 bug

### ISSUE THREAD

**Issue by mzlogin** [ystcode/BlogHelper#21]
![image](https://user-images.githubusercontent.com/1646590/81494376-0eae0480-92db-11ea-8ec2-387532ce028f.png)

**A JavaScript error occurred in the main process**

Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Applications/写作助手.app/Contents/Resources/app.asar/src/blog/oschina.js:127:61)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

试了两个往博客园发布正常的文件都是如此。

**Comment by ystcode** [comment]
感谢，该bug将在1.0.16版本修复。
